name: expanse

services:
  app:
    build: .
    image: expanse:local
    pull_policy: build
    ports:
      - "4000:3000"
    environment:
      - CORE_ONLY=true
      - URL=${APP_URL:-http://localhost:4000}
      - SECRET_KEY=${SECRET_KEY:-please_change_me_to_something_secure}
      - MONGODB_URI=mongodb://${DB_USER:-dev}:${DB_PASS:-dev}@db:27017/expanse?authSource=admin
    depends_on:
      - db
    restart: unless-stopped
    # We need root or being in docker group to access the socket
    user: root
    networks:
      - expanse-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/library:/app/data/library

  db:
    image: mongo:8.2-rc-noble
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-dev}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-dev}
    volumes:
      - expanse_db_data:/data/db
    networks:
      - expanse-net
    restart: unless-stopped

networks:
  expanse-net:
    driver: bridge

volumes:
  expanse_db_data:
